"""
ca-analyzer — M5 色度仪测试模块
Program entry point.

Usage (development):
    python main.py

Usage (production / packaged):
    Run the single-file exe generated by pyinstaller.
"""

import sys

from PySide6.QtWidgets import QApplication
from src.main_window import MainWindow


def main() -> None:
    app = QApplication(sys.argv)
    app.setApplicationName('CA-410 色度分析仪')
    app.setApplicationVersion('1.0.0')

    window = MainWindow()
    window.show()

    sys.exit(app.exec())


if __name__ == '__main__':
    main()
